# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f796240acc64d14ab0670cd62f33c1c4e1f8878aef7fe5074dc7e15ab4867e9d6cd99cb8c025c7042c2939341bb321966e8ff53444a6f2209d353a29df73f765

test:
  secret_key_base: 94851e7693842fdca34ded9852561d628efb0750e251cca253114c5fbe9c27f123988a19818b870bc88f867b72ad1d75f4af5f88441276d4787eb95b6372f94e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
